/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AAmpNameAndExpressionNoName extends PAndExpressionNoName
{
    private PAndExpressionNoName _andExpressionNoName_;
    private TAmp _amp_;
    private PName _name_;

    public AAmpNameAndExpressionNoName()
    {
        // Constructor
    }

    public AAmpNameAndExpressionNoName(
        @SuppressWarnings("hiding") PAndExpressionNoName _andExpressionNoName_,
        @SuppressWarnings("hiding") TAmp _amp_,
        @SuppressWarnings("hiding") PName _name_)
    {
        // Constructor
        setAndExpressionNoName(_andExpressionNoName_);

        setAmp(_amp_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new AAmpNameAndExpressionNoName(
            cloneNode(this._andExpressionNoName_),
            cloneNode(this._amp_),
            cloneNode(this._name_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAmpNameAndExpressionNoName(this);
    }

    public PAndExpressionNoName getAndExpressionNoName()
    {
        return this._andExpressionNoName_;
    }

    public void setAndExpressionNoName(PAndExpressionNoName node)
    {
        if(this._andExpressionNoName_ != null)
        {
            this._andExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExpressionNoName_ = node;
    }

    public TAmp getAmp()
    {
        return this._amp_;
    }

    public void setAmp(TAmp node)
    {
        if(this._amp_ != null)
        {
            this._amp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._amp_ = node;
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andExpressionNoName_)
            + toString(this._amp_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andExpressionNoName_ == child)
        {
            this._andExpressionNoName_ = null;
            return;
        }

        if(this._amp_ == child)
        {
            this._amp_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andExpressionNoName_ == oldChild)
        {
            setAndExpressionNoName((PAndExpressionNoName) newChild);
            return;
        }

        if(this._amp_ == oldChild)
        {
            setAmp((TAmp) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
