/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AArrayReferenceType extends PReferenceType
{
    private PArrayType _arrayType_;

    public AArrayReferenceType()
    {
        // Constructor
    }

    public AArrayReferenceType(
        @SuppressWarnings("hiding") PArrayType _arrayType_)
    {
        // Constructor
        setArrayType(_arrayType_);

    }

    @Override
    public Object clone()
    {
        return new AArrayReferenceType(
            cloneNode(this._arrayType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayReferenceType(this);
    }

    public PArrayType getArrayType()
    {
        return this._arrayType_;
    }

    public void setArrayType(PArrayType node)
    {
        if(this._arrayType_ != null)
        {
            this._arrayType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrayType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrayType_ == child)
        {
            this._arrayType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrayType_ == oldChild)
        {
            setArrayType((PArrayType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
