/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AArrayCreationExpressionNoName extends PExpressionNoName
{
    private PArrayCreationExpression _arrayCreationExpression_;

    public AArrayCreationExpressionNoName()
    {
        // Constructor
    }

    public AArrayCreationExpressionNoName(
        @SuppressWarnings("hiding") PArrayCreationExpression _arrayCreationExpression_)
    {
        // Constructor
        setArrayCreationExpression(_arrayCreationExpression_);

    }

    @Override
    public Object clone()
    {
        return new AArrayCreationExpressionNoName(
            cloneNode(this._arrayCreationExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayCreationExpressionNoName(this);
    }

    public PArrayCreationExpression getArrayCreationExpression()
    {
        return this._arrayCreationExpression_;
    }

    public void setArrayCreationExpression(PArrayCreationExpression node)
    {
        if(this._arrayCreationExpression_ != null)
        {
            this._arrayCreationExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayCreationExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrayCreationExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrayCreationExpression_ == child)
        {
            this._arrayCreationExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrayCreationExpression_ == oldChild)
        {
            setArrayCreationExpression((PArrayCreationExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
