/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ABarNameInclusiveOrExpressionNoName extends PInclusiveOrExpressionNoName
{
    private PInclusiveOrExpressionNoName _inclusiveOrExpressionNoName_;
    private TBar _bar_;
    private PName _name_;

    public ABarNameInclusiveOrExpressionNoName()
    {
        // Constructor
    }

    public ABarNameInclusiveOrExpressionNoName(
        @SuppressWarnings("hiding") PInclusiveOrExpressionNoName _inclusiveOrExpressionNoName_,
        @SuppressWarnings("hiding") TBar _bar_,
        @SuppressWarnings("hiding") PName _name_)
    {
        // Constructor
        setInclusiveOrExpressionNoName(_inclusiveOrExpressionNoName_);

        setBar(_bar_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new ABarNameInclusiveOrExpressionNoName(
            cloneNode(this._inclusiveOrExpressionNoName_),
            cloneNode(this._bar_),
            cloneNode(this._name_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABarNameInclusiveOrExpressionNoName(this);
    }

    public PInclusiveOrExpressionNoName getInclusiveOrExpressionNoName()
    {
        return this._inclusiveOrExpressionNoName_;
    }

    public void setInclusiveOrExpressionNoName(PInclusiveOrExpressionNoName node)
    {
        if(this._inclusiveOrExpressionNoName_ != null)
        {
            this._inclusiveOrExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inclusiveOrExpressionNoName_ = node;
    }

    public TBar getBar()
    {
        return this._bar_;
    }

    public void setBar(TBar node)
    {
        if(this._bar_ != null)
        {
            this._bar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bar_ = node;
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inclusiveOrExpressionNoName_)
            + toString(this._bar_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inclusiveOrExpressionNoName_ == child)
        {
            this._inclusiveOrExpressionNoName_ = null;
            return;
        }

        if(this._bar_ == child)
        {
            this._bar_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inclusiveOrExpressionNoName_ == oldChild)
        {
            setInclusiveOrExpressionNoName((PInclusiveOrExpressionNoName) newChild);
            return;
        }

        if(this._bar_ == oldChild)
        {
            setBar((TBar) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
