/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanPrimitiveType extends PPrimitiveType
{
    private TBooleanKeyword _booleanKeyword_;

    public ABooleanPrimitiveType()
    {
        // Constructor
    }

    public ABooleanPrimitiveType(
        @SuppressWarnings("hiding") TBooleanKeyword _booleanKeyword_)
    {
        // Constructor
        setBooleanKeyword(_booleanKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanPrimitiveType(
            cloneNode(this._booleanKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanPrimitiveType(this);
    }

    public TBooleanKeyword getBooleanKeyword()
    {
        return this._booleanKeyword_;
    }

    public void setBooleanKeyword(TBooleanKeyword node)
    {
        if(this._booleanKeyword_ != null)
        {
            this._booleanKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanKeyword_ == child)
        {
            this._booleanKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanKeyword_ == oldChild)
        {
            setBooleanKeyword((TBooleanKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
