/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ABoundAdditionalBoundList extends PAdditionalBoundList
{
    private PAdditionalBound _additionalBound_;

    public ABoundAdditionalBoundList()
    {
        // Constructor
    }

    public ABoundAdditionalBoundList(
        @SuppressWarnings("hiding") PAdditionalBound _additionalBound_)
    {
        // Constructor
        setAdditionalBound(_additionalBound_);

    }

    @Override
    public Object clone()
    {
        return new ABoundAdditionalBoundList(
            cloneNode(this._additionalBound_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoundAdditionalBoundList(this);
    }

    public PAdditionalBound getAdditionalBound()
    {
        return this._additionalBound_;
    }

    public void setAdditionalBound(PAdditionalBound node)
    {
        if(this._additionalBound_ != null)
        {
            this._additionalBound_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._additionalBound_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._additionalBound_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._additionalBound_ == child)
        {
            this._additionalBound_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._additionalBound_ == oldChild)
        {
            setAdditionalBound((PAdditionalBound) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
