/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ACaretNameExclusiveOrExpressionNoName extends PExclusiveOrExpressionNoName
{
    private PExclusiveOrExpressionNoName _exclusiveOrExpressionNoName_;
    private TCaret _caret_;
    private PName _name_;

    public ACaretNameExclusiveOrExpressionNoName()
    {
        // Constructor
    }

    public ACaretNameExclusiveOrExpressionNoName(
        @SuppressWarnings("hiding") PExclusiveOrExpressionNoName _exclusiveOrExpressionNoName_,
        @SuppressWarnings("hiding") TCaret _caret_,
        @SuppressWarnings("hiding") PName _name_)
    {
        // Constructor
        setExclusiveOrExpressionNoName(_exclusiveOrExpressionNoName_);

        setCaret(_caret_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new ACaretNameExclusiveOrExpressionNoName(
            cloneNode(this._exclusiveOrExpressionNoName_),
            cloneNode(this._caret_),
            cloneNode(this._name_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaretNameExclusiveOrExpressionNoName(this);
    }

    public PExclusiveOrExpressionNoName getExclusiveOrExpressionNoName()
    {
        return this._exclusiveOrExpressionNoName_;
    }

    public void setExclusiveOrExpressionNoName(PExclusiveOrExpressionNoName node)
    {
        if(this._exclusiveOrExpressionNoName_ != null)
        {
            this._exclusiveOrExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclusiveOrExpressionNoName_ = node;
    }

    public TCaret getCaret()
    {
        return this._caret_;
    }

    public void setCaret(TCaret node)
    {
        if(this._caret_ != null)
        {
            this._caret_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caret_ = node;
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exclusiveOrExpressionNoName_)
            + toString(this._caret_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exclusiveOrExpressionNoName_ == child)
        {
            this._exclusiveOrExpressionNoName_ = null;
            return;
        }

        if(this._caret_ == child)
        {
            this._caret_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exclusiveOrExpressionNoName_ == oldChild)
        {
            setExclusiveOrExpressionNoName((PExclusiveOrExpressionNoName) newChild);
            return;
        }

        if(this._caret_ == oldChild)
        {
            setCaret((TCaret) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
