/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ACharIntegralType extends PIntegralType
{
    private TCharKeyword _charKeyword_;

    public ACharIntegralType()
    {
        // Constructor
    }

    public ACharIntegralType(
        @SuppressWarnings("hiding") TCharKeyword _charKeyword_)
    {
        // Constructor
        setCharKeyword(_charKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ACharIntegralType(
            cloneNode(this._charKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACharIntegralType(this);
    }

    public TCharKeyword getCharKeyword()
    {
        return this._charKeyword_;
    }

    public void setCharKeyword(TCharKeyword node)
    {
        if(this._charKeyword_ != null)
        {
            this._charKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charKeyword_ == child)
        {
            this._charKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charKeyword_ == oldChild)
        {
            setCharKeyword((TCharKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
