/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AClassClassDeclaration extends PClassDeclaration
{
    private PNormalClassDeclaration _normalClassDeclaration_;

    public AClassClassDeclaration()
    {
        // Constructor
    }

    public AClassClassDeclaration(
        @SuppressWarnings("hiding") PNormalClassDeclaration _normalClassDeclaration_)
    {
        // Constructor
        setNormalClassDeclaration(_normalClassDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AClassClassDeclaration(
            cloneNode(this._normalClassDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassClassDeclaration(this);
    }

    public PNormalClassDeclaration getNormalClassDeclaration()
    {
        return this._normalClassDeclaration_;
    }

    public void setNormalClassDeclaration(PNormalClassDeclaration node)
    {
        if(this._normalClassDeclaration_ != null)
        {
            this._normalClassDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._normalClassDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._normalClassDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._normalClassDeclaration_ == child)
        {
            this._normalClassDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._normalClassDeclaration_ == oldChild)
        {
            setNormalClassDeclaration((PNormalClassDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
