/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AClauseCatches extends PCatches
{
    private PCatchClause _catchClause_;

    public AClauseCatches()
    {
        // Constructor
    }

    public AClauseCatches(
        @SuppressWarnings("hiding") PCatchClause _catchClause_)
    {
        // Constructor
        setCatchClause(_catchClause_);

    }

    @Override
    public Object clone()
    {
        return new AClauseCatches(
            cloneNode(this._catchClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClauseCatches(this);
    }

    public PCatchClause getCatchClause()
    {
        return this._catchClause_;
    }

    public void setCatchClause(PCatchClause node)
    {
        if(this._catchClause_ != null)
        {
            this._catchClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._catchClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._catchClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._catchClause_ == child)
        {
            this._catchClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._catchClause_ == oldChild)
        {
            setCatchClause((PCatchClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
