/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AComponentDeclaration extends PComponentDeclaration
{
    private PModifiers _modifiers_;
    private TComponentKeyword _componentKeyword_;
    private TDefinitionKeyword _definitionKeyword_;
    private TIdentifier _identifier_;
    private PTypeParameters _typeParameters_;
    private PComponentBody _componentBody_;

    public AComponentDeclaration()
    {
        // Constructor
    }

    public AComponentDeclaration(
        @SuppressWarnings("hiding") PModifiers _modifiers_,
        @SuppressWarnings("hiding") TComponentKeyword _componentKeyword_,
        @SuppressWarnings("hiding") TDefinitionKeyword _definitionKeyword_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PTypeParameters _typeParameters_,
        @SuppressWarnings("hiding") PComponentBody _componentBody_)
    {
        // Constructor
        setModifiers(_modifiers_);

        setComponentKeyword(_componentKeyword_);

        setDefinitionKeyword(_definitionKeyword_);

        setIdentifier(_identifier_);

        setTypeParameters(_typeParameters_);

        setComponentBody(_componentBody_);

    }

    @Override
    public Object clone()
    {
        return new AComponentDeclaration(
            cloneNode(this._modifiers_),
            cloneNode(this._componentKeyword_),
            cloneNode(this._definitionKeyword_),
            cloneNode(this._identifier_),
            cloneNode(this._typeParameters_),
            cloneNode(this._componentBody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComponentDeclaration(this);
    }

    public PModifiers getModifiers()
    {
        return this._modifiers_;
    }

    public void setModifiers(PModifiers node)
    {
        if(this._modifiers_ != null)
        {
            this._modifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modifiers_ = node;
    }

    public TComponentKeyword getComponentKeyword()
    {
        return this._componentKeyword_;
    }

    public void setComponentKeyword(TComponentKeyword node)
    {
        if(this._componentKeyword_ != null)
        {
            this._componentKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._componentKeyword_ = node;
    }

    public TDefinitionKeyword getDefinitionKeyword()
    {
        return this._definitionKeyword_;
    }

    public void setDefinitionKeyword(TDefinitionKeyword node)
    {
        if(this._definitionKeyword_ != null)
        {
            this._definitionKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definitionKeyword_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PTypeParameters getTypeParameters()
    {
        return this._typeParameters_;
    }

    public void setTypeParameters(PTypeParameters node)
    {
        if(this._typeParameters_ != null)
        {
            this._typeParameters_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeParameters_ = node;
    }

    public PComponentBody getComponentBody()
    {
        return this._componentBody_;
    }

    public void setComponentBody(PComponentBody node)
    {
        if(this._componentBody_ != null)
        {
            this._componentBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._componentBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._modifiers_)
            + toString(this._componentKeyword_)
            + toString(this._definitionKeyword_)
            + toString(this._identifier_)
            + toString(this._typeParameters_)
            + toString(this._componentBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._modifiers_ == child)
        {
            this._modifiers_ = null;
            return;
        }

        if(this._componentKeyword_ == child)
        {
            this._componentKeyword_ = null;
            return;
        }

        if(this._definitionKeyword_ == child)
        {
            this._definitionKeyword_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._typeParameters_ == child)
        {
            this._typeParameters_ = null;
            return;
        }

        if(this._componentBody_ == child)
        {
            this._componentBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._modifiers_ == oldChild)
        {
            setModifiers((PModifiers) newChild);
            return;
        }

        if(this._componentKeyword_ == oldChild)
        {
            setComponentKeyword((TComponentKeyword) newChild);
            return;
        }

        if(this._definitionKeyword_ == oldChild)
        {
            setDefinitionKeyword((TDefinitionKeyword) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._typeParameters_ == oldChild)
        {
            setTypeParameters((PTypeParameters) newChild);
            return;
        }

        if(this._componentBody_ == oldChild)
        {
            setComponentBody((PComponentBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
