/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AComponentTypeDeclaration extends PTypeDeclaration
{
    private PComponentDeclaration _componentDeclaration_;

    public AComponentTypeDeclaration()
    {
        // Constructor
    }

    public AComponentTypeDeclaration(
        @SuppressWarnings("hiding") PComponentDeclaration _componentDeclaration_)
    {
        // Constructor
        setComponentDeclaration(_componentDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AComponentTypeDeclaration(
            cloneNode(this._componentDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComponentTypeDeclaration(this);
    }

    public PComponentDeclaration getComponentDeclaration()
    {
        return this._componentDeclaration_;
    }

    public void setComponentDeclaration(PComponentDeclaration node)
    {
        if(this._componentDeclaration_ != null)
        {
            this._componentDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._componentDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._componentDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._componentDeclaration_ == child)
        {
            this._componentDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._componentDeclaration_ == oldChild)
        {
            setComponentDeclaration((PComponentDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
