/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AConstantNameSwitchLabel extends PSwitchLabel
{
    private PName _case_;

    public AConstantNameSwitchLabel()
    {
        // Constructor
    }

    public AConstantNameSwitchLabel(
        @SuppressWarnings("hiding") PName _case_)
    {
        // Constructor
        setCase(_case_);

    }

    @Override
    public Object clone()
    {
        return new AConstantNameSwitchLabel(
            cloneNode(this._case_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstantNameSwitchLabel(this);
    }

    public PName getCase()
    {
        return this._case_;
    }

    public void setCase(PName node)
    {
        if(this._case_ != null)
        {
            this._case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._case_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._case_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._case_ == child)
        {
            this._case_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._case_ == oldChild)
        {
            setCase((PName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
