/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AConstantEnumConstants extends PEnumConstants
{
    private PEnumConstant _enumConstant_;

    public AConstantEnumConstants()
    {
        // Constructor
    }

    public AConstantEnumConstants(
        @SuppressWarnings("hiding") PEnumConstant _enumConstant_)
    {
        // Constructor
        setEnumConstant(_enumConstant_);

    }

    @Override
    public Object clone()
    {
        return new AConstantEnumConstants(
            cloneNode(this._enumConstant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstantEnumConstants(this);
    }

    public PEnumConstant getEnumConstant()
    {
        return this._enumConstant_;
    }

    public void setEnumConstant(PEnumConstant node)
    {
        if(this._enumConstant_ != null)
        {
            this._enumConstant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enumConstant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enumConstant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enumConstant_ == child)
        {
            this._enumConstant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enumConstant_ == oldChild)
        {
            setEnumConstant((PEnumConstant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
