/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AConstantSwitchLabel extends PSwitchLabel
{
    private TCaseKeyword _caseKeyword_;
    private PConstantExpressionNoName _constantExpressionNoName_;
    private TColon _colon_;

    public AConstantSwitchLabel()
    {
        // Constructor
    }

    public AConstantSwitchLabel(
        @SuppressWarnings("hiding") TCaseKeyword _caseKeyword_,
        @SuppressWarnings("hiding") PConstantExpressionNoName _constantExpressionNoName_,
        @SuppressWarnings("hiding") TColon _colon_)
    {
        // Constructor
        setCaseKeyword(_caseKeyword_);

        setConstantExpressionNoName(_constantExpressionNoName_);

        setColon(_colon_);

    }

    @Override
    public Object clone()
    {
        return new AConstantSwitchLabel(
            cloneNode(this._caseKeyword_),
            cloneNode(this._constantExpressionNoName_),
            cloneNode(this._colon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstantSwitchLabel(this);
    }

    public TCaseKeyword getCaseKeyword()
    {
        return this._caseKeyword_;
    }

    public void setCaseKeyword(TCaseKeyword node)
    {
        if(this._caseKeyword_ != null)
        {
            this._caseKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caseKeyword_ = node;
    }

    public PConstantExpressionNoName getConstantExpressionNoName()
    {
        return this._constantExpressionNoName_;
    }

    public void setConstantExpressionNoName(PConstantExpressionNoName node)
    {
        if(this._constantExpressionNoName_ != null)
        {
            this._constantExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constantExpressionNoName_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caseKeyword_)
            + toString(this._constantExpressionNoName_)
            + toString(this._colon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caseKeyword_ == child)
        {
            this._caseKeyword_ = null;
            return;
        }

        if(this._constantExpressionNoName_ == child)
        {
            this._constantExpressionNoName_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caseKeyword_ == oldChild)
        {
            setCaseKeyword((TCaseKeyword) newChild);
            return;
        }

        if(this._constantExpressionNoName_ == oldChild)
        {
            setConstantExpressionNoName((PConstantExpressionNoName) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
