/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AConnectStatement extends PConnectStatement
{
    private TIdentifier _providedId_;
    private TIdentifier _requiredId_;
    private PClassType _classType_;

    public AConnectStatement()
    {
        // Constructor
    }

    public AConnectStatement(
        @SuppressWarnings("hiding") TIdentifier _providedId_,
        @SuppressWarnings("hiding") TIdentifier _requiredId_,
        @SuppressWarnings("hiding") PClassType _classType_)
    {
        // Constructor
        setProvidedId(_providedId_);

        setRequiredId(_requiredId_);

        setClassType(_classType_);

    }

    @Override
    public Object clone()
    {
        return new AConnectStatement(
            cloneNode(this._providedId_),
            cloneNode(this._requiredId_),
            cloneNode(this._classType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConnectStatement(this);
    }

    public TIdentifier getProvidedId()
    {
        return this._providedId_;
    }

    public void setProvidedId(TIdentifier node)
    {
        if(this._providedId_ != null)
        {
            this._providedId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._providedId_ = node;
    }

    public TIdentifier getRequiredId()
    {
        return this._requiredId_;
    }

    public void setRequiredId(TIdentifier node)
    {
        if(this._requiredId_ != null)
        {
            this._requiredId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._requiredId_ = node;
    }

    public PClassType getClassType()
    {
        return this._classType_;
    }

    public void setClassType(PClassType node)
    {
        if(this._classType_ != null)
        {
            this._classType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._providedId_)
            + toString(this._requiredId_)
            + toString(this._classType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._providedId_ == child)
        {
            this._providedId_ = null;
            return;
        }

        if(this._requiredId_ == child)
        {
            this._requiredId_ = null;
            return;
        }

        if(this._classType_ == child)
        {
            this._classType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._providedId_ == oldChild)
        {
            setProvidedId((TIdentifier) newChild);
            return;
        }

        if(this._requiredId_ == oldChild)
        {
            setRequiredId((TIdentifier) newChild);
            return;
        }

        if(this._classType_ == oldChild)
        {
            setClassType((PClassType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
