/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ADeclarationsTypeDeclarations extends PTypeDeclarations
{
    private PTypeDeclarations _typeDeclarations_;
    private PTypeDeclaration _typeDeclaration_;

    public ADeclarationsTypeDeclarations()
    {
        // Constructor
    }

    public ADeclarationsTypeDeclarations(
        @SuppressWarnings("hiding") PTypeDeclarations _typeDeclarations_,
        @SuppressWarnings("hiding") PTypeDeclaration _typeDeclaration_)
    {
        // Constructor
        setTypeDeclarations(_typeDeclarations_);

        setTypeDeclaration(_typeDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ADeclarationsTypeDeclarations(
            cloneNode(this._typeDeclarations_),
            cloneNode(this._typeDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarationsTypeDeclarations(this);
    }

    public PTypeDeclarations getTypeDeclarations()
    {
        return this._typeDeclarations_;
    }

    public void setTypeDeclarations(PTypeDeclarations node)
    {
        if(this._typeDeclarations_ != null)
        {
            this._typeDeclarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDeclarations_ = node;
    }

    public PTypeDeclaration getTypeDeclaration()
    {
        return this._typeDeclaration_;
    }

    public void setTypeDeclaration(PTypeDeclaration node)
    {
        if(this._typeDeclaration_ != null)
        {
            this._typeDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeDeclarations_)
            + toString(this._typeDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeDeclarations_ == child)
        {
            this._typeDeclarations_ = null;
            return;
        }

        if(this._typeDeclaration_ == child)
        {
            this._typeDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeDeclarations_ == oldChild)
        {
            setTypeDeclarations((PTypeDeclarations) newChild);
            return;
        }

        if(this._typeDeclaration_ == oldChild)
        {
            setTypeDeclaration((PTypeDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
