/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ADetailsAssertStatement extends PAssertStatement
{
    private PExpression _cond_;
    private PExpression _msg_;

    public ADetailsAssertStatement()
    {
        // Constructor
    }

    public ADetailsAssertStatement(
        @SuppressWarnings("hiding") PExpression _cond_,
        @SuppressWarnings("hiding") PExpression _msg_)
    {
        // Constructor
        setCond(_cond_);

        setMsg(_msg_);

    }

    @Override
    public Object clone()
    {
        return new ADetailsAssertStatement(
            cloneNode(this._cond_),
            cloneNode(this._msg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADetailsAssertStatement(this);
    }

    public PExpression getCond()
    {
        return this._cond_;
    }

    public void setCond(PExpression node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    public PExpression getMsg()
    {
        return this._msg_;
    }

    public void setMsg(PExpression node)
    {
        if(this._msg_ != null)
        {
            this._msg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._msg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond_)
            + toString(this._msg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        if(this._msg_ == child)
        {
            this._msg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond_ == oldChild)
        {
            setCond((PExpression) newChild);
            return;
        }

        if(this._msg_ == oldChild)
        {
            setMsg((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
