/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AEnumClassDeclaration extends PClassDeclaration
{
    private PEnumDeclaration _enumDeclaration_;

    public AEnumClassDeclaration()
    {
        // Constructor
    }

    public AEnumClassDeclaration(
        @SuppressWarnings("hiding") PEnumDeclaration _enumDeclaration_)
    {
        // Constructor
        setEnumDeclaration(_enumDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AEnumClassDeclaration(
            cloneNode(this._enumDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnumClassDeclaration(this);
    }

    public PEnumDeclaration getEnumDeclaration()
    {
        return this._enumDeclaration_;
    }

    public void setEnumDeclaration(PEnumDeclaration node)
    {
        if(this._enumDeclaration_ != null)
        {
            this._enumDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enumDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enumDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enumDeclaration_ == child)
        {
            this._enumDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enumDeclaration_ == oldChild)
        {
            setEnumDeclaration((PEnumDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
