/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import java.util.*;
import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AEnumBody extends PEnumBody
{
    private final LinkedList<PEnumConstant> _enumConstant_ = new LinkedList<PEnumConstant>();
    private final LinkedList<PClassBodyDeclaration> _classBodyDeclaration_ = new LinkedList<PClassBodyDeclaration>();

    public AEnumBody()
    {
        // Constructor
    }

    public AEnumBody(
        @SuppressWarnings("hiding") List<?> _enumConstant_,
        @SuppressWarnings("hiding") List<?> _classBodyDeclaration_)
    {
        // Constructor
        setEnumConstant(_enumConstant_);

        setClassBodyDeclaration(_classBodyDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AEnumBody(
            cloneList(this._enumConstant_),
            cloneList(this._classBodyDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnumBody(this);
    }

    public LinkedList<PEnumConstant> getEnumConstant()
    {
        return this._enumConstant_;
    }

    public void setEnumConstant(List<?> list)
    {
        for(PEnumConstant e : this._enumConstant_)
        {
            e.parent(null);
        }
        this._enumConstant_.clear();

        for(Object obj_e : list)
        {
            PEnumConstant e = (PEnumConstant) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._enumConstant_.add(e);
        }
    }

    public LinkedList<PClassBodyDeclaration> getClassBodyDeclaration()
    {
        return this._classBodyDeclaration_;
    }

    public void setClassBodyDeclaration(List<?> list)
    {
        for(PClassBodyDeclaration e : this._classBodyDeclaration_)
        {
            e.parent(null);
        }
        this._classBodyDeclaration_.clear();

        for(Object obj_e : list)
        {
            PClassBodyDeclaration e = (PClassBodyDeclaration) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._classBodyDeclaration_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enumConstant_)
            + toString(this._classBodyDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enumConstant_.remove(child))
        {
            return;
        }

        if(this._classBodyDeclaration_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PEnumConstant> i = this._enumConstant_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PEnumConstant) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PClassBodyDeclaration> i = this._classBodyDeclaration_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PClassBodyDeclaration) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
