/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AEqEqualityExpressionNoName extends PEqualityExpressionNoName
{
    private PEqualityExpressionNoName _equalityExpressionNoName_;
    private TEq _eq_;
    private PRelationalExpressionNoName _relationalExpressionNoName_;

    public AEqEqualityExpressionNoName()
    {
        // Constructor
    }

    public AEqEqualityExpressionNoName(
        @SuppressWarnings("hiding") PEqualityExpressionNoName _equalityExpressionNoName_,
        @SuppressWarnings("hiding") TEq _eq_,
        @SuppressWarnings("hiding") PRelationalExpressionNoName _relationalExpressionNoName_)
    {
        // Constructor
        setEqualityExpressionNoName(_equalityExpressionNoName_);

        setEq(_eq_);

        setRelationalExpressionNoName(_relationalExpressionNoName_);

    }

    @Override
    public Object clone()
    {
        return new AEqEqualityExpressionNoName(
            cloneNode(this._equalityExpressionNoName_),
            cloneNode(this._eq_),
            cloneNode(this._relationalExpressionNoName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqEqualityExpressionNoName(this);
    }

    public PEqualityExpressionNoName getEqualityExpressionNoName()
    {
        return this._equalityExpressionNoName_;
    }

    public void setEqualityExpressionNoName(PEqualityExpressionNoName node)
    {
        if(this._equalityExpressionNoName_ != null)
        {
            this._equalityExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExpressionNoName_ = node;
    }

    public TEq getEq()
    {
        return this._eq_;
    }

    public void setEq(TEq node)
    {
        if(this._eq_ != null)
        {
            this._eq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eq_ = node;
    }

    public PRelationalExpressionNoName getRelationalExpressionNoName()
    {
        return this._relationalExpressionNoName_;
    }

    public void setRelationalExpressionNoName(PRelationalExpressionNoName node)
    {
        if(this._relationalExpressionNoName_ != null)
        {
            this._relationalExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalExpressionNoName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityExpressionNoName_)
            + toString(this._eq_)
            + toString(this._relationalExpressionNoName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityExpressionNoName_ == child)
        {
            this._equalityExpressionNoName_ = null;
            return;
        }

        if(this._eq_ == child)
        {
            this._eq_ = null;
            return;
        }

        if(this._relationalExpressionNoName_ == child)
        {
            this._relationalExpressionNoName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityExpressionNoName_ == oldChild)
        {
            setEqualityExpressionNoName((PEqualityExpressionNoName) newChild);
            return;
        }

        if(this._eq_ == oldChild)
        {
            setEq((TEq) newChild);
            return;
        }

        if(this._relationalExpressionNoName_ == oldChild)
        {
            setRelationalExpressionNoName((PRelationalExpressionNoName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
