/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AExprDimExprs extends PDimExprs
{
    private PDimExpr _dimExpr_;

    public AExprDimExprs()
    {
        // Constructor
    }

    public AExprDimExprs(
        @SuppressWarnings("hiding") PDimExpr _dimExpr_)
    {
        // Constructor
        setDimExpr(_dimExpr_);

    }

    @Override
    public Object clone()
    {
        return new AExprDimExprs(
            cloneNode(this._dimExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprDimExprs(this);
    }

    public PDimExpr getDimExpr()
    {
        return this._dimExpr_;
    }

    public void setDimExpr(PDimExpr node)
    {
        if(this._dimExpr_ != null)
        {
            this._dimExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dimExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dimExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dimExpr_ == child)
        {
            this._dimExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dimExpr_ == oldChild)
        {
            setDimExpr((PDimExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
