/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AExpressionThrowStatement extends PThrowStatement
{
    private TThrowKeyword _throwKeyword_;
    private PExpressionNoName _expressionNoName_;
    private TSemi _semi_;

    public AExpressionThrowStatement()
    {
        // Constructor
    }

    public AExpressionThrowStatement(
        @SuppressWarnings("hiding") TThrowKeyword _throwKeyword_,
        @SuppressWarnings("hiding") PExpressionNoName _expressionNoName_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setThrowKeyword(_throwKeyword_);

        setExpressionNoName(_expressionNoName_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AExpressionThrowStatement(
            cloneNode(this._throwKeyword_),
            cloneNode(this._expressionNoName_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionThrowStatement(this);
    }

    public TThrowKeyword getThrowKeyword()
    {
        return this._throwKeyword_;
    }

    public void setThrowKeyword(TThrowKeyword node)
    {
        if(this._throwKeyword_ != null)
        {
            this._throwKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._throwKeyword_ = node;
    }

    public PExpressionNoName getExpressionNoName()
    {
        return this._expressionNoName_;
    }

    public void setExpressionNoName(PExpressionNoName node)
    {
        if(this._expressionNoName_ != null)
        {
            this._expressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionNoName_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._throwKeyword_)
            + toString(this._expressionNoName_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._throwKeyword_ == child)
        {
            this._throwKeyword_ = null;
            return;
        }

        if(this._expressionNoName_ == child)
        {
            this._expressionNoName_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._throwKeyword_ == oldChild)
        {
            setThrowKeyword((TThrowKeyword) newChild);
            return;
        }

        if(this._expressionNoName_ == oldChild)
        {
            setExpressionNoName((PExpressionNoName) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
