/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AForStatementStatementNoShortIf extends PStatementNoShortIf
{
    private PForStatementNoShortIf _forStatementNoShortIf_;

    public AForStatementStatementNoShortIf()
    {
        // Constructor
    }

    public AForStatementStatementNoShortIf(
        @SuppressWarnings("hiding") PForStatementNoShortIf _forStatementNoShortIf_)
    {
        // Constructor
        setForStatementNoShortIf(_forStatementNoShortIf_);

    }

    @Override
    public Object clone()
    {
        return new AForStatementStatementNoShortIf(
            cloneNode(this._forStatementNoShortIf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForStatementStatementNoShortIf(this);
    }

    public PForStatementNoShortIf getForStatementNoShortIf()
    {
        return this._forStatementNoShortIf_;
    }

    public void setForStatementNoShortIf(PForStatementNoShortIf node)
    {
        if(this._forStatementNoShortIf_ != null)
        {
            this._forStatementNoShortIf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forStatementNoShortIf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forStatementNoShortIf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forStatementNoShortIf_ == child)
        {
            this._forStatementNoShortIf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forStatementNoShortIf_ == oldChild)
        {
            setForStatementNoShortIf((PForStatementNoShortIf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
