/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AHeaderFields extends PHeaderFields
{
    private PFormalParameterList _formalParameterList_;

    public AHeaderFields()
    {
        // Constructor
    }

    public AHeaderFields(
        @SuppressWarnings("hiding") PFormalParameterList _formalParameterList_)
    {
        // Constructor
        setFormalParameterList(_formalParameterList_);

    }

    @Override
    public Object clone()
    {
        return new AHeaderFields(
            cloneNode(this._formalParameterList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHeaderFields(this);
    }

    public PFormalParameterList getFormalParameterList()
    {
        return this._formalParameterList_;
    }

    public void setFormalParameterList(PFormalParameterList node)
    {
        if(this._formalParameterList_ != null)
        {
            this._formalParameterList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formalParameterList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formalParameterList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formalParameterList_ == child)
        {
            this._formalParameterList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formalParameterList_ == oldChild)
        {
            setFormalParameterList((PFormalParameterList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
