/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AInitDeclaration extends PInitDeclaration
{
    private PModifiers _modifiers_;
    private TInitKeyword _initKeyword_;
    private PHeaderFields _headerFields_;
    private PConstructorBody _constructorBody_;

    public AInitDeclaration()
    {
        // Constructor
    }

    public AInitDeclaration(
        @SuppressWarnings("hiding") PModifiers _modifiers_,
        @SuppressWarnings("hiding") TInitKeyword _initKeyword_,
        @SuppressWarnings("hiding") PHeaderFields _headerFields_,
        @SuppressWarnings("hiding") PConstructorBody _constructorBody_)
    {
        // Constructor
        setModifiers(_modifiers_);

        setInitKeyword(_initKeyword_);

        setHeaderFields(_headerFields_);

        setConstructorBody(_constructorBody_);

    }

    @Override
    public Object clone()
    {
        return new AInitDeclaration(
            cloneNode(this._modifiers_),
            cloneNode(this._initKeyword_),
            cloneNode(this._headerFields_),
            cloneNode(this._constructorBody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitDeclaration(this);
    }

    public PModifiers getModifiers()
    {
        return this._modifiers_;
    }

    public void setModifiers(PModifiers node)
    {
        if(this._modifiers_ != null)
        {
            this._modifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modifiers_ = node;
    }

    public TInitKeyword getInitKeyword()
    {
        return this._initKeyword_;
    }

    public void setInitKeyword(TInitKeyword node)
    {
        if(this._initKeyword_ != null)
        {
            this._initKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initKeyword_ = node;
    }

    public PHeaderFields getHeaderFields()
    {
        return this._headerFields_;
    }

    public void setHeaderFields(PHeaderFields node)
    {
        if(this._headerFields_ != null)
        {
            this._headerFields_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._headerFields_ = node;
    }

    public PConstructorBody getConstructorBody()
    {
        return this._constructorBody_;
    }

    public void setConstructorBody(PConstructorBody node)
    {
        if(this._constructorBody_ != null)
        {
            this._constructorBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constructorBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._modifiers_)
            + toString(this._initKeyword_)
            + toString(this._headerFields_)
            + toString(this._constructorBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._modifiers_ == child)
        {
            this._modifiers_ = null;
            return;
        }

        if(this._initKeyword_ == child)
        {
            this._initKeyword_ = null;
            return;
        }

        if(this._headerFields_ == child)
        {
            this._headerFields_ = null;
            return;
        }

        if(this._constructorBody_ == child)
        {
            this._constructorBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._modifiers_ == oldChild)
        {
            setModifiers((PModifiers) newChild);
            return;
        }

        if(this._initKeyword_ == oldChild)
        {
            setInitKeyword((TInitKeyword) newChild);
            return;
        }

        if(this._headerFields_ == oldChild)
        {
            setHeaderFields((PHeaderFields) newChild);
            return;
        }

        if(this._constructorBody_ == oldChild)
        {
            setConstructorBody((PConstructorBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
