/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AInitComponentBodyDeclaration extends PComponentBodyDeclaration
{
    private PInitDeclaration _initDeclaration_;

    public AInitComponentBodyDeclaration()
    {
        // Constructor
    }

    public AInitComponentBodyDeclaration(
        @SuppressWarnings("hiding") PInitDeclaration _initDeclaration_)
    {
        // Constructor
        setInitDeclaration(_initDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AInitComponentBodyDeclaration(
            cloneNode(this._initDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitComponentBodyDeclaration(this);
    }

    public PInitDeclaration getInitDeclaration()
    {
        return this._initDeclaration_;
    }

    public void setInitDeclaration(PInitDeclaration node)
    {
        if(this._initDeclaration_ != null)
        {
            this._initDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._initDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._initDeclaration_ == child)
        {
            this._initDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._initDeclaration_ == oldChild)
        {
            setInitDeclaration((PInitDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
