/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AListInterfaceTypeList extends PInterfaceTypeList
{
    private PInterfaceTypeList _interfaceTypeList_;
    private TComma _comma_;
    private PInterfaceType _interfaceType_;

    public AListInterfaceTypeList()
    {
        // Constructor
    }

    public AListInterfaceTypeList(
        @SuppressWarnings("hiding") PInterfaceTypeList _interfaceTypeList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PInterfaceType _interfaceType_)
    {
        // Constructor
        setInterfaceTypeList(_interfaceTypeList_);

        setComma(_comma_);

        setInterfaceType(_interfaceType_);

    }

    @Override
    public Object clone()
    {
        return new AListInterfaceTypeList(
            cloneNode(this._interfaceTypeList_),
            cloneNode(this._comma_),
            cloneNode(this._interfaceType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListInterfaceTypeList(this);
    }

    public PInterfaceTypeList getInterfaceTypeList()
    {
        return this._interfaceTypeList_;
    }

    public void setInterfaceTypeList(PInterfaceTypeList node)
    {
        if(this._interfaceTypeList_ != null)
        {
            this._interfaceTypeList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._interfaceTypeList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PInterfaceType getInterfaceType()
    {
        return this._interfaceType_;
    }

    public void setInterfaceType(PInterfaceType node)
    {
        if(this._interfaceType_ != null)
        {
            this._interfaceType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._interfaceType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._interfaceTypeList_)
            + toString(this._comma_)
            + toString(this._interfaceType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._interfaceTypeList_ == child)
        {
            this._interfaceTypeList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._interfaceType_ == child)
        {
            this._interfaceType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._interfaceTypeList_ == oldChild)
        {
            setInterfaceTypeList((PInterfaceTypeList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._interfaceType_ == oldChild)
        {
            setInterfaceType((PInterfaceType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
