/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import java.util.*;
import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ANameVariableInitializersNoName extends PVariableInitializersNoName
{
    private PName _name_;
    private final LinkedList<PVariableInitializersTail> _variableInitializersTail_ = new LinkedList<PVariableInitializersTail>();

    public ANameVariableInitializersNoName()
    {
        // Constructor
    }

    public ANameVariableInitializersNoName(
        @SuppressWarnings("hiding") PName _name_,
        @SuppressWarnings("hiding") List<?> _variableInitializersTail_)
    {
        // Constructor
        setName(_name_);

        setVariableInitializersTail(_variableInitializersTail_);

    }

    @Override
    public Object clone()
    {
        return new ANameVariableInitializersNoName(
            cloneNode(this._name_),
            cloneList(this._variableInitializersTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameVariableInitializersNoName(this);
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public LinkedList<PVariableInitializersTail> getVariableInitializersTail()
    {
        return this._variableInitializersTail_;
    }

    public void setVariableInitializersTail(List<?> list)
    {
        for(PVariableInitializersTail e : this._variableInitializersTail_)
        {
            e.parent(null);
        }
        this._variableInitializersTail_.clear();

        for(Object obj_e : list)
        {
            PVariableInitializersTail e = (PVariableInitializersTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._variableInitializersTail_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._variableInitializersTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._variableInitializersTail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        for(ListIterator<PVariableInitializersTail> i = this._variableInitializersTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVariableInitializersTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
