/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ANameBarConditionalOrExpressionNoName extends PConditionalOrExpressionNoName
{
    private PName _name_;
    private TBarBar _barBar_;
    private PConditionalAndExpressionNoName _conditionalAndExpressionNoName_;

    public ANameBarConditionalOrExpressionNoName()
    {
        // Constructor
    }

    public ANameBarConditionalOrExpressionNoName(
        @SuppressWarnings("hiding") PName _name_,
        @SuppressWarnings("hiding") TBarBar _barBar_,
        @SuppressWarnings("hiding") PConditionalAndExpressionNoName _conditionalAndExpressionNoName_)
    {
        // Constructor
        setName(_name_);

        setBarBar(_barBar_);

        setConditionalAndExpressionNoName(_conditionalAndExpressionNoName_);

    }

    @Override
    public Object clone()
    {
        return new ANameBarConditionalOrExpressionNoName(
            cloneNode(this._name_),
            cloneNode(this._barBar_),
            cloneNode(this._conditionalAndExpressionNoName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameBarConditionalOrExpressionNoName(this);
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TBarBar getBarBar()
    {
        return this._barBar_;
    }

    public void setBarBar(TBarBar node)
    {
        if(this._barBar_ != null)
        {
            this._barBar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barBar_ = node;
    }

    public PConditionalAndExpressionNoName getConditionalAndExpressionNoName()
    {
        return this._conditionalAndExpressionNoName_;
    }

    public void setConditionalAndExpressionNoName(PConditionalAndExpressionNoName node)
    {
        if(this._conditionalAndExpressionNoName_ != null)
        {
            this._conditionalAndExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalAndExpressionNoName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._barBar_)
            + toString(this._conditionalAndExpressionNoName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._barBar_ == child)
        {
            this._barBar_ = null;
            return;
        }

        if(this._conditionalAndExpressionNoName_ == child)
        {
            this._conditionalAndExpressionNoName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        if(this._barBar_ == oldChild)
        {
            setBarBar((TBarBar) newChild);
            return;
        }

        if(this._conditionalAndExpressionNoName_ == oldChild)
        {
            setConditionalAndExpressionNoName((PConditionalAndExpressionNoName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
