/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ANameBarInclusiveOrExpressionNoName extends PInclusiveOrExpressionNoName
{
    private PName _name_;
    private TBar _bar_;
    private PExclusiveOrExpressionNoName _exclusiveOrExpressionNoName_;

    public ANameBarInclusiveOrExpressionNoName()
    {
        // Constructor
    }

    public ANameBarInclusiveOrExpressionNoName(
        @SuppressWarnings("hiding") PName _name_,
        @SuppressWarnings("hiding") TBar _bar_,
        @SuppressWarnings("hiding") PExclusiveOrExpressionNoName _exclusiveOrExpressionNoName_)
    {
        // Constructor
        setName(_name_);

        setBar(_bar_);

        setExclusiveOrExpressionNoName(_exclusiveOrExpressionNoName_);

    }

    @Override
    public Object clone()
    {
        return new ANameBarInclusiveOrExpressionNoName(
            cloneNode(this._name_),
            cloneNode(this._bar_),
            cloneNode(this._exclusiveOrExpressionNoName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameBarInclusiveOrExpressionNoName(this);
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TBar getBar()
    {
        return this._bar_;
    }

    public void setBar(TBar node)
    {
        if(this._bar_ != null)
        {
            this._bar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bar_ = node;
    }

    public PExclusiveOrExpressionNoName getExclusiveOrExpressionNoName()
    {
        return this._exclusiveOrExpressionNoName_;
    }

    public void setExclusiveOrExpressionNoName(PExclusiveOrExpressionNoName node)
    {
        if(this._exclusiveOrExpressionNoName_ != null)
        {
            this._exclusiveOrExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclusiveOrExpressionNoName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._bar_)
            + toString(this._exclusiveOrExpressionNoName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._bar_ == child)
        {
            this._bar_ = null;
            return;
        }

        if(this._exclusiveOrExpressionNoName_ == child)
        {
            this._exclusiveOrExpressionNoName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        if(this._bar_ == oldChild)
        {
            setBar((TBar) newChild);
            return;
        }

        if(this._exclusiveOrExpressionNoName_ == oldChild)
        {
            setExclusiveOrExpressionNoName((PExclusiveOrExpressionNoName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
