/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ANameAmpConditionalAndExpressionNoName extends PConditionalAndExpressionNoName
{
    private PName _name_;
    private TAmpAmp _ampAmp_;
    private PInclusiveOrExpressionNoName _inclusiveOrExpressionNoName_;

    public ANameAmpConditionalAndExpressionNoName()
    {
        // Constructor
    }

    public ANameAmpConditionalAndExpressionNoName(
        @SuppressWarnings("hiding") PName _name_,
        @SuppressWarnings("hiding") TAmpAmp _ampAmp_,
        @SuppressWarnings("hiding") PInclusiveOrExpressionNoName _inclusiveOrExpressionNoName_)
    {
        // Constructor
        setName(_name_);

        setAmpAmp(_ampAmp_);

        setInclusiveOrExpressionNoName(_inclusiveOrExpressionNoName_);

    }

    @Override
    public Object clone()
    {
        return new ANameAmpConditionalAndExpressionNoName(
            cloneNode(this._name_),
            cloneNode(this._ampAmp_),
            cloneNode(this._inclusiveOrExpressionNoName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameAmpConditionalAndExpressionNoName(this);
    }

    public PName getName()
    {
        return this._name_;
    }

    public void setName(PName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TAmpAmp getAmpAmp()
    {
        return this._ampAmp_;
    }

    public void setAmpAmp(TAmpAmp node)
    {
        if(this._ampAmp_ != null)
        {
            this._ampAmp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ampAmp_ = node;
    }

    public PInclusiveOrExpressionNoName getInclusiveOrExpressionNoName()
    {
        return this._inclusiveOrExpressionNoName_;
    }

    public void setInclusiveOrExpressionNoName(PInclusiveOrExpressionNoName node)
    {
        if(this._inclusiveOrExpressionNoName_ != null)
        {
            this._inclusiveOrExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inclusiveOrExpressionNoName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._ampAmp_)
            + toString(this._inclusiveOrExpressionNoName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._ampAmp_ == child)
        {
            this._ampAmp_ = null;
            return;
        }

        if(this._inclusiveOrExpressionNoName_ == child)
        {
            this._inclusiveOrExpressionNoName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((PName) newChild);
            return;
        }

        if(this._ampAmp_ == oldChild)
        {
            setAmpAmp((TAmpAmp) newChild);
            return;
        }

        if(this._inclusiveOrExpressionNoName_ == oldChild)
        {
            setInclusiveOrExpressionNoName((PInclusiveOrExpressionNoName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
