/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ANativeModifier extends PModifier
{
    private TNativeKeyword _nativeKeyword_;

    public ANativeModifier()
    {
        // Constructor
    }

    public ANativeModifier(
        @SuppressWarnings("hiding") TNativeKeyword _nativeKeyword_)
    {
        // Constructor
        setNativeKeyword(_nativeKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ANativeModifier(
            cloneNode(this._nativeKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANativeModifier(this);
    }

    public TNativeKeyword getNativeKeyword()
    {
        return this._nativeKeyword_;
    }

    public void setNativeKeyword(TNativeKeyword node)
    {
        if(this._nativeKeyword_ != null)
        {
            this._nativeKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nativeKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nativeKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nativeKeyword_ == child)
        {
            this._nativeKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nativeKeyword_ == oldChild)
        {
            setNativeKeyword((TNativeKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
