/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AParameterFormalParameterList extends PFormalParameterList
{
    private PLastFormalParameter _lastFormalParameter_;

    public AParameterFormalParameterList()
    {
        // Constructor
    }

    public AParameterFormalParameterList(
        @SuppressWarnings("hiding") PLastFormalParameter _lastFormalParameter_)
    {
        // Constructor
        setLastFormalParameter(_lastFormalParameter_);

    }

    @Override
    public Object clone()
    {
        return new AParameterFormalParameterList(
            cloneNode(this._lastFormalParameter_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterFormalParameterList(this);
    }

    public PLastFormalParameter getLastFormalParameter()
    {
        return this._lastFormalParameter_;
    }

    public void setLastFormalParameter(PLastFormalParameter node)
    {
        if(this._lastFormalParameter_ != null)
        {
            this._lastFormalParameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lastFormalParameter_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lastFormalParameter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lastFormalParameter_ == child)
        {
            this._lastFormalParameter_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lastFormalParameter_ == oldChild)
        {
            setLastFormalParameter((PLastFormalParameter) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
