/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class APortTypeDeclaration extends PTypeDeclaration
{
    private PPortDeclaration _portDeclaration_;

    public APortTypeDeclaration()
    {
        // Constructor
    }

    public APortTypeDeclaration(
        @SuppressWarnings("hiding") PPortDeclaration _portDeclaration_)
    {
        // Constructor
        setPortDeclaration(_portDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new APortTypeDeclaration(
            cloneNode(this._portDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPortTypeDeclaration(this);
    }

    public PPortDeclaration getPortDeclaration()
    {
        return this._portDeclaration_;
    }

    public void setPortDeclaration(PPortDeclaration node)
    {
        if(this._portDeclaration_ != null)
        {
            this._portDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._portDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._portDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._portDeclaration_ == child)
        {
            this._portDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._portDeclaration_ == oldChild)
        {
            setPortDeclaration((PPortDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
