/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class APostfixPostIncrementExpression extends PPostIncrementExpression
{
    private PPostfixExpressionNoName _postfixExpressionNoName_;
    private TPlusPlus _plusPlus_;

    public APostfixPostIncrementExpression()
    {
        // Constructor
    }

    public APostfixPostIncrementExpression(
        @SuppressWarnings("hiding") PPostfixExpressionNoName _postfixExpressionNoName_,
        @SuppressWarnings("hiding") TPlusPlus _plusPlus_)
    {
        // Constructor
        setPostfixExpressionNoName(_postfixExpressionNoName_);

        setPlusPlus(_plusPlus_);

    }

    @Override
    public Object clone()
    {
        return new APostfixPostIncrementExpression(
            cloneNode(this._postfixExpressionNoName_),
            cloneNode(this._plusPlus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostfixPostIncrementExpression(this);
    }

    public PPostfixExpressionNoName getPostfixExpressionNoName()
    {
        return this._postfixExpressionNoName_;
    }

    public void setPostfixExpressionNoName(PPostfixExpressionNoName node)
    {
        if(this._postfixExpressionNoName_ != null)
        {
            this._postfixExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._postfixExpressionNoName_ = node;
    }

    public TPlusPlus getPlusPlus()
    {
        return this._plusPlus_;
    }

    public void setPlusPlus(TPlusPlus node)
    {
        if(this._plusPlus_ != null)
        {
            this._plusPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusPlus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._postfixExpressionNoName_)
            + toString(this._plusPlus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._postfixExpressionNoName_ == child)
        {
            this._postfixExpressionNoName_ = null;
            return;
        }

        if(this._plusPlus_ == child)
        {
            this._plusPlus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._postfixExpressionNoName_ == oldChild)
        {
            setPostfixExpressionNoName((PPostfixExpressionNoName) newChild);
            return;
        }

        if(this._plusPlus_ == oldChild)
        {
            setPlusPlus((TPlusPlus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
