/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ARequestDeclaration extends PRequestDeclaration
{
    private PClassType _classType_;

    public ARequestDeclaration()
    {
        // Constructor
    }

    public ARequestDeclaration(
        @SuppressWarnings("hiding") PClassType _classType_)
    {
        // Constructor
        setClassType(_classType_);

    }

    @Override
    public Object clone()
    {
        return new ARequestDeclaration(
            cloneNode(this._classType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARequestDeclaration(this);
    }

    public PClassType getClassType()
    {
        return this._classType_;
    }

    public void setClassType(PClassType node)
    {
        if(this._classType_ != null)
        {
            this._classType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classType_ == child)
        {
            this._classType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classType_ == oldChild)
        {
            setClassType((PClassType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
