/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AStaticKolaModifier extends PKolaModifier
{
    private TStaticKeyword _staticKeyword_;

    public AStaticKolaModifier()
    {
        // Constructor
    }

    public AStaticKolaModifier(
        @SuppressWarnings("hiding") TStaticKeyword _staticKeyword_)
    {
        // Constructor
        setStaticKeyword(_staticKeyword_);

    }

    @Override
    public Object clone()
    {
        return new AStaticKolaModifier(
            cloneNode(this._staticKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStaticKolaModifier(this);
    }

    public TStaticKeyword getStaticKeyword()
    {
        return this._staticKeyword_;
    }

    public void setStaticKeyword(TStaticKeyword node)
    {
        if(this._staticKeyword_ != null)
        {
            this._staticKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._staticKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._staticKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._staticKeyword_ == child)
        {
            this._staticKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._staticKeyword_ == oldChild)
        {
            setStaticKeyword((TStaticKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
