/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AStarMultiplicativeExpressionNoName extends PMultiplicativeExpressionNoName
{
    private PMultiplicativeExpressionNoName _multiplicativeExpressionNoName_;
    private TStar _star_;
    private PUnaryExpressionNoName _unaryExpressionNoName_;

    public AStarMultiplicativeExpressionNoName()
    {
        // Constructor
    }

    public AStarMultiplicativeExpressionNoName(
        @SuppressWarnings("hiding") PMultiplicativeExpressionNoName _multiplicativeExpressionNoName_,
        @SuppressWarnings("hiding") TStar _star_,
        @SuppressWarnings("hiding") PUnaryExpressionNoName _unaryExpressionNoName_)
    {
        // Constructor
        setMultiplicativeExpressionNoName(_multiplicativeExpressionNoName_);

        setStar(_star_);

        setUnaryExpressionNoName(_unaryExpressionNoName_);

    }

    @Override
    public Object clone()
    {
        return new AStarMultiplicativeExpressionNoName(
            cloneNode(this._multiplicativeExpressionNoName_),
            cloneNode(this._star_),
            cloneNode(this._unaryExpressionNoName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStarMultiplicativeExpressionNoName(this);
    }

    public PMultiplicativeExpressionNoName getMultiplicativeExpressionNoName()
    {
        return this._multiplicativeExpressionNoName_;
    }

    public void setMultiplicativeExpressionNoName(PMultiplicativeExpressionNoName node)
    {
        if(this._multiplicativeExpressionNoName_ != null)
        {
            this._multiplicativeExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiplicativeExpressionNoName_ = node;
    }

    public TStar getStar()
    {
        return this._star_;
    }

    public void setStar(TStar node)
    {
        if(this._star_ != null)
        {
            this._star_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._star_ = node;
    }

    public PUnaryExpressionNoName getUnaryExpressionNoName()
    {
        return this._unaryExpressionNoName_;
    }

    public void setUnaryExpressionNoName(PUnaryExpressionNoName node)
    {
        if(this._unaryExpressionNoName_ != null)
        {
            this._unaryExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExpressionNoName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiplicativeExpressionNoName_)
            + toString(this._star_)
            + toString(this._unaryExpressionNoName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiplicativeExpressionNoName_ == child)
        {
            this._multiplicativeExpressionNoName_ = null;
            return;
        }

        if(this._star_ == child)
        {
            this._star_ = null;
            return;
        }

        if(this._unaryExpressionNoName_ == child)
        {
            this._unaryExpressionNoName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multiplicativeExpressionNoName_ == oldChild)
        {
            setMultiplicativeExpressionNoName((PMultiplicativeExpressionNoName) newChild);
            return;
        }

        if(this._star_ == oldChild)
        {
            setStar((TStar) newChild);
            return;
        }

        if(this._unaryExpressionNoName_ == oldChild)
        {
            setUnaryExpressionNoName((PUnaryExpressionNoName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
