/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AStaticImportDeclaration extends PImportDeclaration
{
    private PSingleStaticImportDeclaration _singleStaticImportDeclaration_;

    public AStaticImportDeclaration()
    {
        // Constructor
    }

    public AStaticImportDeclaration(
        @SuppressWarnings("hiding") PSingleStaticImportDeclaration _singleStaticImportDeclaration_)
    {
        // Constructor
        setSingleStaticImportDeclaration(_singleStaticImportDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AStaticImportDeclaration(
            cloneNode(this._singleStaticImportDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStaticImportDeclaration(this);
    }

    public PSingleStaticImportDeclaration getSingleStaticImportDeclaration()
    {
        return this._singleStaticImportDeclaration_;
    }

    public void setSingleStaticImportDeclaration(PSingleStaticImportDeclaration node)
    {
        if(this._singleStaticImportDeclaration_ != null)
        {
            this._singleStaticImportDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleStaticImportDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._singleStaticImportDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._singleStaticImportDeclaration_ == child)
        {
            this._singleStaticImportDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._singleStaticImportDeclaration_ == oldChild)
        {
            setSingleStaticImportDeclaration((PSingleStaticImportDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
