/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ASubscribeStatement extends PSubscribeStatement
{
    private TIdentifier _handlerId_;
    private TIdentifier _portId_;

    public ASubscribeStatement()
    {
        // Constructor
    }

    public ASubscribeStatement(
        @SuppressWarnings("hiding") TIdentifier _handlerId_,
        @SuppressWarnings("hiding") TIdentifier _portId_)
    {
        // Constructor
        setHandlerId(_handlerId_);

        setPortId(_portId_);

    }

    @Override
    public Object clone()
    {
        return new ASubscribeStatement(
            cloneNode(this._handlerId_),
            cloneNode(this._portId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubscribeStatement(this);
    }

    public TIdentifier getHandlerId()
    {
        return this._handlerId_;
    }

    public void setHandlerId(TIdentifier node)
    {
        if(this._handlerId_ != null)
        {
            this._handlerId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._handlerId_ = node;
    }

    public TIdentifier getPortId()
    {
        return this._portId_;
    }

    public void setPortId(TIdentifier node)
    {
        if(this._portId_ != null)
        {
            this._portId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._portId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._handlerId_)
            + toString(this._portId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._handlerId_ == child)
        {
            this._handlerId_ = null;
            return;
        }

        if(this._portId_ == child)
        {
            this._portId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._handlerId_ == oldChild)
        {
            setHandlerId((TIdentifier) newChild);
            return;
        }

        if(this._portId_ == oldChild)
        {
            setPortId((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
