/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ATildeUnaryExpressionNotPlusMinusNoName extends PUnaryExpressionNotPlusMinusNoName
{
    private TTilde _tilde_;
    private PUnaryExpressionNoName _unaryExpressionNoName_;

    public ATildeUnaryExpressionNotPlusMinusNoName()
    {
        // Constructor
    }

    public ATildeUnaryExpressionNotPlusMinusNoName(
        @SuppressWarnings("hiding") TTilde _tilde_,
        @SuppressWarnings("hiding") PUnaryExpressionNoName _unaryExpressionNoName_)
    {
        // Constructor
        setTilde(_tilde_);

        setUnaryExpressionNoName(_unaryExpressionNoName_);

    }

    @Override
    public Object clone()
    {
        return new ATildeUnaryExpressionNotPlusMinusNoName(
            cloneNode(this._tilde_),
            cloneNode(this._unaryExpressionNoName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATildeUnaryExpressionNotPlusMinusNoName(this);
    }

    public TTilde getTilde()
    {
        return this._tilde_;
    }

    public void setTilde(TTilde node)
    {
        if(this._tilde_ != null)
        {
            this._tilde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tilde_ = node;
    }

    public PUnaryExpressionNoName getUnaryExpressionNoName()
    {
        return this._unaryExpressionNoName_;
    }

    public void setUnaryExpressionNoName(PUnaryExpressionNoName node)
    {
        if(this._unaryExpressionNoName_ != null)
        {
            this._unaryExpressionNoName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExpressionNoName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tilde_)
            + toString(this._unaryExpressionNoName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tilde_ == child)
        {
            this._tilde_ = null;
            return;
        }

        if(this._unaryExpressionNoName_ == child)
        {
            this._unaryExpressionNoName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tilde_ == oldChild)
        {
            setTilde((TTilde) newChild);
            return;
        }

        if(this._unaryExpressionNoName_ == oldChild)
        {
            setUnaryExpressionNoName((PUnaryExpressionNoName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
