/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ATriggerKolaKeyword extends PKolaKeyword
{
    private TTriggerKeyword _triggerKeyword_;

    public ATriggerKolaKeyword()
    {
        // Constructor
    }

    public ATriggerKolaKeyword(
        @SuppressWarnings("hiding") TTriggerKeyword _triggerKeyword_)
    {
        // Constructor
        setTriggerKeyword(_triggerKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ATriggerKolaKeyword(
            cloneNode(this._triggerKeyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATriggerKolaKeyword(this);
    }

    public TTriggerKeyword getTriggerKeyword()
    {
        return this._triggerKeyword_;
    }

    public void setTriggerKeyword(TTriggerKeyword node)
    {
        if(this._triggerKeyword_ != null)
        {
            this._triggerKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._triggerKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._triggerKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._triggerKeyword_ == child)
        {
            this._triggerKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._triggerKeyword_ == oldChild)
        {
            setTriggerKeyword((TTriggerKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
