/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class ATypeImportDeclaration extends PImportDeclaration
{
    private PTypeImportOnDemandDeclaration _typeImportOnDemandDeclaration_;

    public ATypeImportDeclaration()
    {
        // Constructor
    }

    public ATypeImportDeclaration(
        @SuppressWarnings("hiding") PTypeImportOnDemandDeclaration _typeImportOnDemandDeclaration_)
    {
        // Constructor
        setTypeImportOnDemandDeclaration(_typeImportOnDemandDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ATypeImportDeclaration(
            cloneNode(this._typeImportOnDemandDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeImportDeclaration(this);
    }

    public PTypeImportOnDemandDeclaration getTypeImportOnDemandDeclaration()
    {
        return this._typeImportOnDemandDeclaration_;
    }

    public void setTypeImportOnDemandDeclaration(PTypeImportOnDemandDeclaration node)
    {
        if(this._typeImportOnDemandDeclaration_ != null)
        {
            this._typeImportOnDemandDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeImportOnDemandDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeImportOnDemandDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeImportOnDemandDeclaration_ == child)
        {
            this._typeImportOnDemandDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeImportOnDemandDeclaration_ == oldChild)
        {
            setTypeImportOnDemandDeclaration((PTypeImportOnDemandDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
