/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class AVoidExpressionNoName extends PExpressionNoName
{

    public AVoidExpressionNoName()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVoidExpressionNoName();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVoidExpressionNoName(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
