/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class TComponentdefKeyword extends Token
{
    public TComponentdefKeyword()
    {
        super.setText("componentdef");
    }

    public TComponentdefKeyword(int line, int pos)
    {
        super.setText("componentdef");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComponentdefKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComponentdefKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComponentdefKeyword text.");
    }
}
