/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class TDefaultKeyword extends Token
{
    public TDefaultKeyword()
    {
        super.setText("default");
    }

    public TDefaultKeyword(int line, int pos)
    {
        super.setText("default");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDefaultKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDefaultKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDefaultKeyword text.");
    }
}
