/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class TImportKeyword extends Token
{
    public TImportKeyword()
    {
        super.setText("import");
    }

    public TImportKeyword(int line, int pos)
    {
        super.setText("import");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TImportKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTImportKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TImportKeyword text.");
    }
}
