/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class TInitKeyword extends Token
{
    public TInitKeyword()
    {
        super.setText("init");
    }

    public TInitKeyword(int line, int pos)
    {
        super.setText("init");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInitKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInitKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInitKeyword text.");
    }
}
