/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class TPrivateKeyword extends Token
{
    public TPrivateKeyword()
    {
        super.setText("private");
    }

    public TPrivateKeyword(int line, int pos)
    {
        super.setText("private");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrivateKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrivateKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrivateKeyword text.");
    }
}
