/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class TSubscribeKeyword extends Token
{
    public TSubscribeKeyword()
    {
        super.setText("!subscribe");
    }

    public TSubscribeKeyword(int line, int pos)
    {
        super.setText("!subscribe");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSubscribeKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSubscribeKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSubscribeKeyword text.");
    }
}
