/* This file was generated by SableCC (http://www.sablecc.org/). */

package se.sics.kola.node;

import se.sics.kola.analysis.*;

@SuppressWarnings("nls")
public final class TThrowsKeyword extends Token
{
    public TThrowsKeyword()
    {
        super.setText("throws");
    }

    public TThrowsKeyword(int line, int pos)
    {
        super.setText("throws");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThrowsKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThrowsKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThrowsKeyword text.");
    }
}
